### ISSUE TITLE
Draw :-/ smile on UNSTABLE status

### ISSUE THREAD

**Issue by k-bx** [ataylor284/jenkins-watch#3]
We have tons of lint-tests that check for style and coverage, so our jenkins is almost always UNSTABLE status. As I see, jenkins-watch still thinks it's an error.

**Comment by ataylor284** [comment]
That's a good suggestion.  I'll take at look at it.

**Comment by ataylor284** [comment]
Added (finally).  Thanks for the suggestion.

**Comment by k-bx** [comment]
Cool. thanks!
