### ISSUE TITLE
Install/configure instructions in README?

### ISSUE THREAD

**Issue by bitops** [ataylor284/jenkins-watch#4]
Hello, jenkins-watch looks cool. It would be nice if there were some basic installation & configuration instructions in the README; which variables need to be defined in init.el, requires, etc.

Thanks!

**Comment by ataylor284** [comment]
Ok, I've added some install instructions.  Thanks for the suggestion and feedback on the change is welcome.

**Comment by bitops** [comment]
Looks great! Thank you. :+1:
